name: Building Program
run-name: Building ${{ GITHUB.REPOSITORY }}

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  call-tianlu:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-tianlu.yml@master
    secrets: inherit
